version: "3.7"

services:
  # cassandra-seed:
  #   container_name: cassandra-seed
  #   image: cassandra
  #   ports: 
  #     - "9042:9042"
  #   environment:
  #     - CASSANDRA_SEEDS=cassandra-seed
  #     - CASSANDRA_CLUSTER_NAME=Cassandra Cluster
  #     - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
  #     - CASSANDRA_DC=DC1
  #   restart: always
  #   volumes:
  #     - ./docker/volumes/cassandra-seed:/var/lib/cassandra
  #   networks: 
  #     - cass
  #   healthcheck:
  #     test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 50

  # cassandra-node:
  #   container_name: cassandra-node
  #   image: cassandra
  #   environment:
  #     - CASSANDRA_SEEDS=cassandra-seed
  #     - CASSANDRA_CLUSTER_NAME=Cassandra Cluster
  #     - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
  #     - CASSANDRA_DC=DC1
  #   restart: always
  #   volumes: 
  #     - ./docker/volumes/cassandra-node:/var/lib/cassandra
  #   depends_on: 
  #     - cassandra-seed
  #   networks: 
  #     - cass
  #   healthcheck:
  #     test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 50

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./docker/volumes/zookeeper/data:/data
      - ./docker/volumes/zookeeper/conf:/conf
    networks:
      - kafka

  kafka:
    container_name: kafka
    hostname: kafka
    image: "wurstmeister/kafka:0.10.2.0"
    ports:
     - "9092:9092"
    expose:
     - "9093"
    links:
     - zookeeper
    environment:
     - KAFKA_ADVERTISED_HOST_NAME=kafka
     - KAFKA_ADVERTISED_PORT=9092
     - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9093, OUTSIDE://localhost:9092
     - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT, OUTSIDE:PLAINTEXT
     - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
     - KAFKA_LISTENERS=INSIDE://0.0.0.0:9093, OUTSIDE://0.0.0.0:9092
     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    #  - KAFKA_CREATE_TOPICS="twitter:3:1"
    volumes:
      - ./docker/volumes/kafka:/kafka/kafka-logs-kafka
    networks:
      - kafka

networks:
  kafka:
  cass:
